### ISSUE TITLE
SSSD will not boot up after enabled All recording

### ISSUE THREAD

**Issue by lzap** [Scribery/cockpit-session-recording#157]
Hello,

I installed a fresh Fedora 38, installed Session Recording, enabled All recording and SSSD does not start anymore. The error is: `Condition ConditionPathExists=/etc/sssd/sssd.conf was not met`. I think previously it was booting up properly, so I wonder if session recording plugin deletes that file or somehow modifies configuration.

Thanks.

**Comment by lzap** [comment]
No other error than this line:

```
index.js:12 Job for sssd.service failed because the control process exited with error code.
See "systemctl status sssd.service" and "journalctl -xeu sssd.service" for details.
```

Reported as https://bugzilla.redhat.com/show_bug.cgi?id=2247777

Thanks!

**Comment by lzap** [comment]
I was missing a dependency `sssd-proxy-2.9.1-1.fc38.x86_64.rpm` after I installed it works.

Since I did everything from Cockpit, including setup of this feature, shall I file a bug report to automatically install this file when the feature is enabled?

**Comment by justin-stephenson** [comment]
I work on the SSSD team as well, I re-assigned the BZ you reported to cockpit-session-recording and will take care of this.

**Comment by lzap** [comment]
Ah I haven’t realized that. Thanks a bunch.
