### ISSUE TITLE
Cockpit session recordings are not playing on web UI 

### ISSUE THREAD

**Issue by dsputnikk** [Scribery/cockpit-session-recording#174]
Alma 9, install cockpit
Enable Session Recording (journal)
Start Terminal session in Web UI (see msg about record warning). Session Entry appears, user's input appears below "black" player but no video is shown.
Have tried Chromium and Firefox, on the server itself. I've tried localhost:9090 and m.y.i.p:9090

I'm on Alma 9.
Cockpit 300.4
cockpit-session-recording 13

Switching to file or syslog doesn't help. In fact, the session no longer appears as an entry, whether file or syslog. However in file mode, I do get a file in my /tmp directory which I can successfully playback with tlog-play -i thefilename.

I can find no hard errors from sssd or cockpit or selinux.

I see browser warnings for po.js not loading, but other github comments tell me to ignore it.

**Comment by justin-stephenson** [comment]
Hi, can you check that logging in as the recorded user correctly performs session recording (creating tlog_rec entries in the systemd journal)? For example, journalctl shows.

~~~
Jun 01 12:16:27 red tlog-rec[28934]: {"ver":"2.2","host":"red","rec":"0f25700a28c44b599869745e5fda8b0c-7106-121e79","user":"contractor1","term":"xterm-kitty","session":2,"id":1,"pos":0,"timing":"=105x56+82>49+603>1+96>1+88>1+472>1+112>1+104>1+807>2+2>13>
~~~

That can be played back with `tlog-play -r journal -M TLOG_REC=0f25700a28c44b599869745e5fda8b0c-7106-121e79

What happens when you hit 'play' in the WebUI player ? 

Do other cockpit apps work for you (like Terminal, which also embeds a terminal emulator player)?

**Comment by dsputnikk** [comment]
> Hi, can you check that logging in as the recorded user correctly performs session recording (creating tlog_rec entries in the systemd journal)? For example, journalctl shows.
> 
> ```
> Jun 01 12:16:27 red tlog-rec[28934]: {"ver":"2.2","host":"red","rec":"0f25700a28c44b599869745e5fda8b0c-7106-121e79","user":"contractor1","term":"xterm-kitty","session":2,"id":1,"pos":0,"timing":"=105x56+82>49+603>1+96>1+88>1+472>1+112>1+104>1+807>2+2>13>
> ```

Indeed, they are there.

> 
> That can be played back with `tlog-play -r journal -M TLOG_REC=0f25700a28c44b599869745e5fda8b0c-7106-121e79

And I can play them as you say
> 
> What happens when you hit 'play' in the WebUI player ?

I see a black video player, video player controls and Event related info below that.

When I hit play, just below the video player I see some portion of commands being typed in (I selected to capture user input). The "video" finishes playing. Nothing is ever displayed on the "black video player".

> 
> Do other cockpit apps work for you (like Terminal, which also embeds a terminal emulator player)?
Yes, in fact that is my primary test case - although the same thing happens when I SSH normally. (A session is logged, but the video player doesn't work)

I note my default shell is zsh, however I have explicitly set the shell to /bin/bash in recorder-settings and the results are the same.


I also get the following in browsers console:
```

GET
http://localhost:9090/cockpit/@localhost/*/po.manifest.js

GET
http://localhost:9090/cockpit/@localhost/*/po.js

The resource from “http://localhost:9090/cockpit/@localhost/*/po.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
session-recording
The resource from “http://localhost:9090/cockpit/@localhost/*/po.manifest.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
session-recording
GET
http://localhost:9090/cockpit/@localhost/*/po.manifest.js

The resource from “http://localhost:9090/cockpit/@localhost/*/po.manifest.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
session-recording
Loading failed for the <script> with source “http://localhost:9090/cockpit/@localhost/*/po.manifest.js”. session-recording:13:38
GET
http://localhost:9090/cockpit/@localhost/*/po.js

The resource from “http://localhost:9090/cockpit/@localhost/*/po.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
session-recording
Loading failed for the <script> with source “http://localhost:9090/cockpit/@localhost/*/po.js”. session-recording:14:29
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. stylesheets-manager.js:536:12
Content-Security-Policy: The page's settings blocked the loading of a resource at inline ("default-src"). index.js:23:55383
Content-Security-Policy: The page's settings blocked the loading of a resource at inline ("default-src"). index.js:23:55581
Content-Security-Policy: The page's settings blocked the loading of a resource at inline ("default-src"). index.js:23:55959
Content-Security-Policy: The page's settings blocked the loading of a resource at inline ("default-src"). index.js:23:58612
Content-Security-Policy: The page's settings blocked the loading of a resource at inline ("default-src").
```

**Comment by dsputnikk** [comment]
I edited my post for clarity and the image reference disappeared. Here it is again:

![image](https://github.com/Scribery/cockpit-session-recording/assets/13570769/af18c2fc-7128-4536-a7d9-62d63fb44a67)

**Comment by nakacya** [comment]
Try using [Session]-[Style]-[Dark Mode] in the upper right corner of the screen.

**Comment by dsputnikk** [comment]
Wow. Okay. I can see it now :). Thank you

**Comment by justin-stephenson** [comment]
This is something that should be fixed, is it correct the 'Dark' cockpit style prevents viewing text in the cockpit session recording playback?

**Comment by dsputnikk** [comment]
Vice versa I think. Light mode prevents it.

Also it doesn't respect color codes. If I play the same session back via
tlog-play, I get color.
