### ISSUE TITLE
Error getting tlog UID from system.

### ISSUE THREAD

**Issue by rgiordani71** [Scribery/cockpit-session-recording#20]
I've installed cockpit on centos 7 and then followed the instructions to install cockpit-session-recording.
Restarted cockpit service I saw the new entry un left "Session Recording" but when click I receive only this message
**"Error getting tlog UID from system."** 

Which additional configuration should I apply?
Thanks

**Comment by justin-stephenson** [comment]
The command `getent passwd tlog` is run to get the uid of the tlog user, can you check the output of this? That said i'm not sure if cockpit works on RHEL7-equivalent or lower distributions, it is supported on RHEL8 and Feodra.

**Comment by rgiordani71** [comment]
I’m out this week, I’ll check next Monday, thanks

**Comment by rgiordani71** [comment]
Hi, I've just checked what you have requested and this is the answer:
>getent passwd testuser1
testuser1:x:1001:1001:testuser1:/home/testuser1:/usr/bin/tlog-rec-session

and these are the configuration of SSSD:
[domain/local]
id_provider = files

[sssd]
domains = local
services = nss, pam, ssh, sudo

Could you please let me know if I've to create a specific user TLOG and change the bash command for testuser1?
Which service should I run with the TLOG user?
Thanks

**Comment by justin-stephenson** [comment]
Hello,

The red hat RPM issues the following commands upon installation to add the tlog user:
~~~
 groupadd -r tlog
 useradd -r -g tlog -d /var/run/tlog -s /sbin/nologin -c "Tlog terminal I/O logger" tlog
~~~

**Comment by justin-stephenson** [comment]
Closing, please re-open or file a new Issue if the problem persists.
