### ISSUE TITLE
Problem play session with russian symbols (ru_RU.UTF-8)

### ISSUE THREAD

**Issue by kvakanet** [Scribery/cockpit-session-recording#38]
Hello!

When "cockpit-session-recording" do play session recorded with input and output russian symbols. 
I see warnings :
extra input present
extra output present

And into window recorded session russian symbols print not correct.
![c-sr](https://user-images.githubusercontent.com/12164487/77502151-cbf3b280-6e7b-11ea-86f9-310cef7fd3b7.png)

This is recorded session correct print russian symbols, if used cli tlog-play.

**Comment by spbnick** [comment]
Thank you for the report, @kvakanet!
@justin-stephenson, I think this could be caused by incorrect calculation of UTF-8 string length in our JS player code.

**Comment by justin-stephenson** [comment]
Thank you for reporting this issue, I will look into it as time permits - apologies for any delay in advance.

**Comment by justin-stephenson** [comment]
I did some quick tests and was unable to reproduce this, however this should be fixed by the length calculation change using the spread operator in https://github.com/Scribery/cockpit-session-recording/pull/39

**Comment by kvakanet** [comment]
Hello!
I downloaded this patched file and put in /usr/share/cockpit/session-recording
The problem has not disappeared.

**Comment by justin-stephenson** [comment]
@kvakanet I don't think that is enough because the .jsx files need to be re-compiled by Babel/Webpack.

Could you try testing with the unofficial rpm I published here?

https://copr.fedorainfracloud.org/coprs/jstephen/cockpit-session-recording/
https://copr.fedorainfracloud.org/coprs/jstephen/cockpit-session-recording/build/1339812/

If the problem persists, could you provide specific a simple reproducer ?

Thanks a lot!

**Comment by kvakanet** [comment]
Hello @justin-stephenson !
For information i test on Centos7.
Now i downloaded your rpm for Centos8. Package install normal.
The problem has not disappeared.
I attached my short file with russian language.
Thank you.
[russian-tlog.txt](https://github.com/Scribery/cockpit-session-recording/files/4490931/russian-tlog.txt)

**Comment by justin-stephenson** [comment]
Sorry @kvakanet I still have been unable to reproduce the problem, I tried using characters you are seeing the issue with from you txt file, and also some other tests but no issues on my end:

Do you see the same problem with different browsers?

~~~
[jstephen@agalloch cockpit-session-recording]$ export LC_ALL=ru_RU.UTF-8
[jstephen@agalloch cockpit-session-recording]$ ( date; export LC_ALL=ru_RU.UTF-8 ; date +%c)
Пт апр 17 09:26:03 EDT 2020
Пт 17 апр 2020 09:26:03
[jstephen@agalloch cockpit-session-recording]$ ( date; \
>     export LC_ALL=ru_RU.UTF-8 ; \
>     d=$(date +%c | sed 's/ /_/g'); \
>     mkdir /tmp/test; \
>     echo $d > /tmp/test/$d.txt; \
>     echo "with right locale:"; \
>     ls -ltra /tmp/test ; \
>     echo "with 'C' locale:"; \
>     LC_ALL=C ls -ltra /tmp/test )
Пт апр 17 09:26:10 EDT 2020
mkdir: невозможно создать каталог «/tmp/test»: File exists
with right locale:
итого 16
-rw-rw-r--.  1 jstephen jstephen  29 апр 17 09:14 Пт_17_апр_2020_09:14:43.txt
-rw-rw-r--.  1 jstephen jstephen  29 апр 17 09:22 Пт_17_апр_2020_09:22:27.txt
-rw-rw-r--.  1 jstephen jstephen  29 апр 17 09:25 Пт_17_апр_2020_09:25:29.txt
drwxrwxrwt. 29 root     root     640 апр 17 09:26 ..
-rw-rw-r--.  1 jstephen jstephen  29 апр 17 09:26 Пт_17_апр_2020_09:26:10.txt
drwxrwxr-x.  2 jstephen jstephen 120 апр 17 09:26 .
with 'C' locale:
total 16
-rw-rw-r--.  1 jstephen jstephen  29 Apr 17 09:14 ''$'\320\237\321\202''_17_'$'\320\260\320\277\321\200''_2020_09:14:43.txt'
-rw-rw-r--.  1 jstephen jstephen  29 Apr 17 09:22 ''$'\320\237\321\202''_17_'$'\320\260\320\277\321\200''_2020_09:22:27.txt'
-rw-rw-r--.  1 jstephen jstephen  29 Apr 17 09:25 ''$'\320\237\321\202''_17_'$'\320\260\320\277\321\200''_2020_09:25:29.txt'
drwxrwxrwt. 29 root     root     640 Apr 17 09:26  ..
-rw-rw-r--.  1 jstephen jstephen  29 Apr 17 09:26 ''$'\320\237\321\202''_17_'$'\320\260\320\277\321\200''_2020_09:26:10.txt'
drwxrwxr-x.  2 jstephen jstephen 120 Apr 17 09:26  .
[jstephen@agalloch cockpit-session-recording]$ cal
     Апрель 2020    
Пн Вт Ср Чт Пт Сб Вс
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30         
                    
[jstephen@agalloch cockpit-session-recording]$ echo Э
Э
~~~

**Comment by kvakanet** [comment]
@justin-stephenson i see the same problem  in firefox 68esr and chromium 73.
May be problem in cockpit ?
```
cockpit.x86_64                     195.1-1.el7.centos.0.1           @extras     
cockpit-bridge.x86_64              195.1-1.el7.centos.0.1           @extras     
cockpit-session-recording.noarch   3.2.ga4e0cbc-1.el8               @/cockpit-session-recording-3.2.ga4e0cbc-1.el8.noarch
cockpit-system.noarch              195.1-1.el7.centos.0.1           @extras     
cockpit-ws.x86_64                  195.1-1.el7.centos.0.1           @extras     
```
May be ssl self signed do creates problem.

**Comment by justin-stephenson** [comment]
@kvakanet I will spin up a CentOS 7 system and do more testing on my end, will respond back here if I have any findings to report.

**Comment by justin-stephenson** [comment]
@kvakanet I was able to reproduce the issue, i'll continue debugging on my side.

**Comment by justin-stephenson** [comment]
@kvakanet I see the same problem as you describe here on CentOS 7.

I tested the same issue on Fedora 30 and RHEL8 and the recorded session reproduces the correct russian characters. This appears to be a locale issue already fixed in cockpit.

**Comment by kvakanet** [comment]
@justin-stephenson Good :( I thought I was crazy :)
issue already fixed in cockpit but not Centos7 :(
Thank you for test.

P.S: May be issue in systemd service file cockpit.

**Comment by justin-stephenson** [comment]
@kvakanet are you okay to close this issue out?

**Comment by kvakanet** [comment]
@justin-stephenson okay. Close this issue.
Thank you.
